version: "3"
services:
  front:
    image: node:12.11.0-alpine
    # network_mode: "host"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "yarn install
      && yarn start"
